test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

production:
  service: GCS
  project: byggro
  bucket: byggro-production
  credentials: <%= Rails.application.encrypted('config/credentials/google-cloud.json.enc').read %>


# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
