test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: GCS
  project: byggro
  bucket: byggro-development
  credentials: <%= Rails.application.encrypted('config/secrets/google-cloud.json.enc').read %>

production:
  service: GCS
  project: byggro
  bucket: byggro-production
  credentials: <%= Rails.application.encrypted('config/secrets/google-cloud.json.enc').read %>